# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  cv_service:
    build: 
      context: ./cv_service
    container_name: floria_cv_api
    ports:
      - "8000:8000"
    volumes:
      - ./cv_service:/app
    environment:
      - ENVIRONMENT=development

  web:
    build: 
      context: ./web
    container_name: floria_web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_CV_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true 
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - cv_service